version: "3"

services:
  db:
    image: mysql:8.0
    container_name: db-go-twitter
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: superSecret
      MYSQL_DATABASE: go_twitter
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
